### ISSUE TITLE
NPC killed me

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-npcbuffer#2]
He spawned a necromancer unclickable who killed me, no idea if it's one of his spell he casts.

Ok it's the first buff

**Comment by BarbzYHOOL** [comment]
And some spells are not applied on my character (night elf), dunno why, I suppose it's spell related

**Comment by talamortis** [comment]
these are not issues / the necromancer is spawned by a spell assigned in the conf file, and some of the spells applied to the NPC are "target: self flag"

**Comment by BarbzYHOOL** [comment]
Hence why it was a "player" cast and you changed it to "creature" cast for which reason?

**Comment by talamortis** [comment]
I changed it to creature for the reason if a warrior goes to the creature and asks for buffs and the spell needs mana then the warrior will skip that buff where you can assign mana to the npc.
